### ISSUE TITLE
Problem if default branch in git is not master

### ISSUE THREAD

**Issue by kilork** [kilork/hg-git-fast-import#21]
```bash
git config --global init.defaultBranch <name>
```

**Comment by vrubleg** [comment]
Is it better to avoid changing default branch name when `hg-git-fast-import` is used?

**Comment by kilork** [comment]
I do not really remember this bug. Better would be probably fix it, just I am not sure `hg-git-fast-import` is used anywhere nowadays...

**Comment by vrubleg** [comment]
Well, it's the best tool for conversion from Mercurial to Git. I still use it sometimes. It's not that tool that you use every day, but when you need it, it's a lifesaver =)

**Comment by kilork** [comment]
Thanks! Looks like I am spending more time here again, probably this tool will also get some updates...
