### ISSUE TITLE
panic failure with "could not parse requirement: ... share-safe"

### ISSUE THREAD

**Issue by markgalassi** [kilork/hg-git-fast-import#27]
I'm getting the error:

```thread 'main' panicked at 'could not parse requirement: UnknownRequirement("share-safe")', /home/markgalassi/.cargo/registry/src/github.com-1ecc6299db9ec823/hg-parser-0.6.0/src/lib.rs:381:41```

when I operate on fresh repos cloned from sourceforge.  If I operate on the same repo that I cloned a year ago, I have no problem.

To reproduce:

```
hg clone http://hg.code.sf.net/p/math-science-working-groups/code math-science-working-groups
# [... output ...]
hg-git-fast-import single math-science-working-groups > math-science-working-groups.git_bare

thread 'main' panicked at 'could not parse requirement: UnknownRequirement("share-safe")', /home/markgalassi/.cargo/registry/src/github.com-1ecc6299db9ec823/hg-parser-0.6.0/src/lib.rs:381:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by kilork** [comment]
Usually you can safely remove this requirement from file you mentioned on stackoverflow :) I think mercurial is for long time has large part of it implemented in Rust. Just the license they have a kind of poisonous. Would not close this bug, but do not think you should expect quick solution.

**Comment by kilork** [comment]
As https://github.com/kilork/hg-parser/issues/4 is implemented (with no real changes actually) this could be also fixed. I am going to bump dep to version, which supports the share-safe requirement and also add another option to allow to ignore unknown requirements.
